### ISSUE TITLE
Error building the binary

### ISSUE THREAD

**Issue by MrAta** [ahas-sigs/kube-ebpf-exporter#3]
Hi,

I have tried different ways to build the binary either using the provided Make file or `go get` by I keep getting the following error:

```bash
go/src/github.com/ahas-sigs/kube-ebpf-exporter/vendor/github.com/iovisor/gobpf/bcc/module.go:32:10: fatal error: bcc/bpf_common.h: No such file or directory
   32 | #include <bcc/bpf_common.h>
      |          ^~~~~~~~~~~~~~~~~~
```

I was wondering if there's any work around this?

**Comment by huaizong** [comment]
> I was wondering if there's any work around this?

kube-ebpf-exporter way only test on special centos 7.6.1810 version; if your os version match, maybe you need install bcc-devel by command `yum install bcc-devel -y`

**Comment by MrAta** [comment]
Thanks, I was working on an Ubuntu image and could resolve it.

**Comment by weiran11** [comment]
I meet the same problem on centos 7

**Comment by weiran11** [comment]
I meet the same problem on centos 7.6

**Comment by weiran11** [comment]
HI @huaizong , I meet the same problem on centos 7.6
os version: CentOS Linux release 7.6.1810 (Core)
kernel version: 3.10.0-957.el7.x86_64
after command `yum install bcc-devel` was done, only `linux` director found in `/usr/include/bcc/compat`
bcc-devel version: bcc-devel-0.10.0-1.el7.x86_64.
